name: Deploy to Amvera

on:
  push:
    branches:
      - devDK

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push to Amvera
        env:
          AMVERA_PASSWORD: ${{ secrets.AMVERA_PASSWORD }}
        run: |
          git config user.email "ci@github.com"
          git config user.name "GitHub Actions"
          git remote add amvera https://keshetash:${AMVERA_PASSWORD}@git.msk0.amvera.ru/keshetash/blizkie-messenger
          git push amvera devDK:master --force
